title: Bits and Bytes
author: Tanya
email: TanyaSelvog@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Overview of basic unit of information in computing.
theme: minima

show_excerpts: true # set to false to remove excerpts on the homepage
